import type { Metadata } from "next";
import "./globals.css";
import ClientProvider from "@/providers/ClientProvider/ClientProvider";
import Script from "next/script";

export const metadata: Metadata = {
  title: "PRTech Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
       <Script id="tawkto-script" strategy="afterInteractive">
        {`
          var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
          (function(){
            var s1 = document.createElement("script"),
                s0 = document.getElementsByTagName("script")[0];
            s1.async = true;
            s1.src = 'https://embed.tawk.to/68977d3c6ec67e192b924fcb/1j27s2dch';
            s1.charset = 'UTF-8';
            s1.setAttribute('crossorigin', '*');
            s0.parentNode.insertBefore(s1, s0);
          })();
        `}
      </Script>
      <body
        className={`antialiased bg-secondary-50`}
      >
        <ClientProvider>{children}</ClientProvider>
      </body>
    </html>
  );
}
